@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Apr 04 17:25:53 -0500 2023
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim fadd_4bit_struct_tb_behav -key {Behavioral:sim_1:Functional:fadd_4bit_struct_tb} -tclbatch fadd_4bit_struct_tb.tcl -log simulate.log"
call xsim  fadd_4bit_struct_tb_behav -key {Behavioral:sim_1:Functional:fadd_4bit_struct_tb} -tclbatch fadd_4bit_struct_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
